export const AUTHORIZATION_AUDIT_EVENT_TYPES = [
  'ROLE_ASSIGNMENT_GRANT',
  'ROLE_ASSIGNMENT_REVOKE',
  'ROLE_ASSIGNMENT_REPLACE',
  'DATA_SCOPE_UPSERT',
  'DATA_SCOPE_DELETE',
  'DATA_SCOPE_ITEM_REPLACE',
  'CONSTRAINT_RULE_UPSERT',
  'CONSTRAINT_RULE_DELETE',
  'CONSTRAINT_VIOLATION',
  'ORG_UNIT_CREATE',
  'ORG_UNIT_UPDATE',
  'ORG_UNIT_DELETE',
  'USER_UNIT_ASSIGN',
  'USER_UNIT_REMOVE',
  'USER_UNIT_SET_PRIMARY',
  'ROLE_RESOURCE_ASSIGN',
  'TENANT_CREATE',
  'TENANT_UPDATE',
  'TENANT_FREEZE',
  'TENANT_UNFREEZE',
  'TENANT_DECOMMISSION',
  'TENANT_DELETE',
  'PLATFORM_TEMPLATE_INITIALIZE',
  'REQUIREMENT_AWARE_ACCESS',
] as const

export const AUTHORIZATION_AUDIT_EVENT_OPTIONS = AUTHORIZATION_AUDIT_EVENT_TYPES.map((value) => ({
  label: value,
  value,
}))

export const AUTHENTICATION_AUDIT_EVENT_TYPES = [
  'LOGIN',
  'LOGOUT',
  'MFA_BIND',
  'MFA_UNBIND',
  'SESSION_REVOKE',
  'TOKEN_ISSUE',
  'TOKEN_REVOKE',
] as const

export const AUTHENTICATION_AUDIT_EVENT_OPTIONS = AUTHENTICATION_AUDIT_EVENT_TYPES.map((value) => ({
  label: value,
  value,
}))
